name: Daily Scraper

on:
  schedule:
    - cron: '30 19 * * *'  # 1:00 AM IST
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    env:
      FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      GSHEETS_CREDENTIALS: ${{ secrets.GSHEETS_CREDENTIALS }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Write credentials to files
        run: |
          echo "$FIREBASE_CREDENTIALS" > coding-team-profiles-2b0b4df65b4a.json
          echo "$GSHEETS_CREDENTIALS" > gsheet-creds.json

      - name: Run daily scraper
        run: python daily_scraper.py
