[firebase]
type = "service_account"
project_id = "coding-team-profiles"
private_key_id = "2b0b4df65b4aadab859788c4733e44c146a62027"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCWauZsoydktHK0
jPy/cLAbsR86GHNV5CRY0SZCiOK68ekg+gTVUtVfDVyGnVZ10JzsZCK4Sfn6tcWw
67P3y/cYoFFaQc9gzj8cA5GRIb0w3gOM1ZvV+pIB/tXuWA+FbP/pVnndV0XqyNEA
vze19lX1WW931f0haRGEKjuUs+7uPHQAA6dUdrMWsvvzI2n/PBjhow/2lo5Ogigo
vf1eudduqBQhvLHo0giPyN1xPyTqxdugmox8LOOLFx4Iz/JMDTGuD0QDdPbEhGN0
ek99VuIV4gD1hw05vYOZOGBZhn7BWuaRLalpVoq0wrSMNlimcbFLP4ftkN4jvHkD
GObogmebAgMBAAECggEAOYwtm1uyex9kkTotisrAvd9+jHoFSlOuKkLeie8YG6Do
6gJtrfXyh1qzzxbMGOgW2YQYGnzHBInd2CndYU0qPMQ9S7RI9IcD8yJUY3vOh68x
GYUyCWRDzzqhu336djg1Ep9QoYO9zq1E9S2zUU0tJuCwOl9m6IzrtC56PBK5M3Dc
X1cRKlmlaYZCtrqOewkyrjkx/N7mEEPFKwgAQMGUWS1Qd7B62Rg5WtrOh7Ye9hTu
zDyW/o6sNls5q6mhZiCSZLIKpCkwFpJU/+yLH0BTmYjx9wQniX/suZ0E9nu+Ua5Y
h8bBM787/8+5JdLQyZRLPRREnoDRnJ3tYY3/Vdb8nQKBgQDHGP4oeNkDbIAQqzeI
hLGVbJgkO/wXWwxjU2drJSHK+FushHldV4+7PAcJ9n6eL8MWHOwq/Vchq9+qJfME
LOnW/hfVQPecg7X6zgHYDz4m9rMBhTDQXJtIzXNosR6m/WffxZNdMLeq3cTV87u8
MxGmachndlFt/Pgi6t+rX488nQKBgQDBaDlsZ3gYcBzP4KEdtNfl2gKskb00bRvL
ScArjk2Cd2ovj7w93q+HaoN29iiYSiP7EbFmkC4XYVfuLBs5ylBZdE9t1rj0tQWw
pLLd/c7IFGbBKIdiCWov9SsbeCVjWMyJsO+64H+3Ui7czvMXyIKhdCg+Em4SLe3I
o/6Okb4TlwKBgHj9NSY/GhG8k66NfbfWe1xEm8gZM761s7eAba5s6DZB6uPRtTcG
CPBNMDHbu2JBwBnmBZayUYrCua7aVO3KpWfjDXSogFB6sdHx8qjrymc/L9TSrbFR
NYRuZZ3PVMNB5yfTFxRgkJyjHASwkvtxRV6Nlh1Zh26BdgEyHi40agT5AoGAVEWh
n8aF4cAYDcwG5/bAi/quZ5spIgrYrX95KIFc7JgzwH2UvDCnsw2KMu+XSKQlgWR4
NARm0PEtay30vv2UfSXc5jNFa/rke8+H0Iqi6zNYgpmyQ9luV28wVUvInr02gliC
XJ8thydcHAJgkeBgaxE9564IIAu7LE2owV5nwAkCgYEAlpuyzjO0ctefCSlAld7D
wAhZcpZDYJCU5XoWVwpW3uoyXpP9w8Wfr7FKEEjZUnhHCJNpiM/2sCcdPBsj4+ou
4T/kGPEuyWNilRWyeJxRJ3jYcpjTnuwHbSBrYlxY0Jnj6o1bJWBHIy0khuN0ggaq
U5qwTh37PEVvSfHo5EsEcJQ=
-----END PRIVATE KEY-----"""
client_email = "firebase-scraper@coding-team-profiles.iam.gserviceaccount.com"
client_id = "109721718921437162081"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-scraper%40coding-team-profiles.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
